// <auto-generated />
using BasicCommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicCommerce.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BasicCommerceDbContext))]
partial class BasicCommerceDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Tenant", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("Name").IsRequired().HasMaxLength(200);
            b.Property<string>("Slug").IsRequired().HasMaxLength(100);
            b.Property<string>("ContactEmail").IsRequired().HasMaxLength(256);
            b.Property<string>("ContactPhone").HasMaxLength(20);
            b.Property<string>("BusinessIdentificationNumber").HasMaxLength(50);
            b.Property<string>("VatRegistrationNumber").HasMaxLength(50);
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasDefaultValue("BDT");
            b.Property<string>("DefaultLanguage").IsRequired().HasMaxLength(10).HasDefaultValue("en");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("Tenants");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Store", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Name").IsRequired().HasMaxLength(200);
            b.Property<string>("Code").IsRequired().HasMaxLength(20);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Code").IsUnique();
            b.ToTable("Stores");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Email").IsRequired().HasMaxLength(256);
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100);
            b.Property<string>("LastName").IsRequired().HasMaxLength(100);
            b.Property<string>("EmployeeCode").IsRequired().HasMaxLength(20);
            b.Property<string>("PasswordHash").HasMaxLength(500);
            b.Property<string>("Role").IsRequired().HasMaxLength(30);
            b.Property<Guid?>("StoreId");
            b.Property<string>("GoogleId").HasMaxLength(200);
            b.Property<string>("MicrosoftId").HasMaxLength(200);
            b.Property<string>("AuthProvider").IsRequired().HasMaxLength(20).HasDefaultValue("Local");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<string>("PreferredLanguage").IsRequired().HasMaxLength(10).HasDefaultValue("en");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("TenantId", "EmployeeCode").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Product", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Sku").IsRequired().HasMaxLength(50);
            b.Property<string>("Barcode").IsRequired().HasMaxLength(100);
            b.Property<string>("Plu").HasMaxLength(20);
            b.Property<string>("Name").IsRequired().HasMaxLength(200);
            b.Property<string>("NameBn").IsRequired().HasMaxLength(200);
            b.Property<Guid>("CategoryId");
            b.Property<Guid>("VatRateId");
            b.Property<bool>("IsWeightBased").HasDefaultValue(false);
            b.Property<bool>("IsAgeRestricted").HasDefaultValue(false);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("Barcode").IsUnique();
            b.HasIndex("TenantId", "Sku").IsUnique();
            b.ToTable("Products");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Transaction", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("TransactionNumber").IsRequired().HasMaxLength(50);
            b.Property<Guid>("StoreId");
            b.Property<Guid>("TerminalId");
            b.Property<Guid>("CashierId");
            b.Property<Guid?>("CustomerId");
            b.Property<string>("TransactionStatus").IsRequired().HasMaxLength(20).HasDefaultValue("Open");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasDefaultValue("Sale");
            b.Property<decimal>("SubTotal").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("TaxTotal").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("DiscountTotal").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("Total").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("AmountPaid").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("ChangeDue").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<bool>("IsSynced").HasDefaultValue(true);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("CompletedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("TransactionNumber").IsUnique();
            b.HasIndex("TenantId", "StoreId", "CreatedAt");
            b.ToTable("Transactions");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.RewardPointsSettings", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<decimal>("ExchangeRate").HasPrecision(18, 4);
            b.Property<int>("MinimumPointsToUse");
            b.Property<int>("MaximumPointsPerOrder");
            b.Property<decimal>("MaximumRedeemedRate").HasPrecision(5, 4);
            b.Property<decimal>("PurchaseSpendPerPoint").HasPrecision(18, 4);
            b.Property<int>("PointsEarnedPerSpend");
            b.Property<int>("PurchasePointsValidityDays");
            b.Property<decimal>("MinimumOrderTotalForPoints").HasPrecision(18, 4);
            b.Property<int>("PointsForRegistration");
            b.Property<int>("RegistrationPointsValidityDays");
            b.Property<bool>("ActivatePointsImmediately");
            b.Property<bool>("DisplayHowMuchWillBeEarned");
            b.Property<bool>("PointsAccumulatedForAllStores");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("TenantId").IsUnique();
            b.ToTable("RewardPointsSettings");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.RewardPointsAccount", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<Guid>("CustomerId");
            b.Property<Guid?>("StoreId");
            b.Property<int>("TotalEarnedPoints");
            b.Property<int>("UsedPoints");
            b.Property<int>("ExpiredPoints");
            b.Property<int>("PendingPoints");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("TenantId", "CustomerId", "StoreId").IsUnique();
            b.ToTable("RewardPointsAccounts");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.RewardPointsEntry", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("RewardPointsAccountId");
            b.Property<int>("Points");
            b.Property<string>("EntryType").IsRequired().HasMaxLength(30);
            b.Property<bool>("IsActivated");
            b.Property<DateTime?>("ExpiresAt");
            b.Property<Guid?>("TransactionId");
            b.Property<string>("Notes").HasMaxLength(500);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("RewardPointsAccountId", "CreatedAt");
            b.HasIndex("TransactionId");
            b.ToTable("RewardPointsEntries");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.RewardPointsEntry", b =>
        {
            b.HasOne("BasicCommerce.Domain.Entities.RewardPointsAccount", null)
                .WithMany("Entries")
                .HasForeignKey("RewardPointsAccountId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductTag", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Name").IsRequired().HasMaxLength(100);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Name").IsUnique();
            b.ToTable("ProductTags");
        });

        modelBuilder.Entity("ProductTagAssignments", b =>
        {
            b.Property<Guid>("ProductId");
            b.Property<Guid>("ProductTagId");
            b.HasKey("ProductId", "ProductTagId");
            b.HasIndex("ProductTagId");
            b.ToTable("ProductTagAssignments");
        });

        modelBuilder.Entity("ProductTagAssignments", b =>
        {
            b.HasOne("BasicCommerce.Domain.Entities.Product", null)
                .WithMany()
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("BasicCommerce.Domain.Entities.ProductTag", null)
                .WithMany()
                .HasForeignKey("ProductTagId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductReview", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<Guid>("ProductId");
            b.Property<Guid?>("CustomerId");
            b.Property<Guid?>("StoreId");
            b.Property<string>("CustomerName").IsRequired().HasMaxLength(200);
            b.Property<string>("Title").IsRequired().HasMaxLength(300);
            b.Property<string>("ReviewText").IsRequired().HasMaxLength(3000);
            b.Property<int>("Rating");
            b.Property<bool>("IsApproved");
            b.Property<bool>("IsVerifiedPurchase");
            b.Property<int>("HelpfulYesTotal");
            b.Property<int>("HelpfulNoTotal");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("TenantId", "ProductId", "CreatedAt");
            b.HasIndex("TenantId", "CustomerId");
            b.ToTable("ProductReviews");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductReviewDetail", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("ProductReviewId");
            b.Property<string>("Comment").IsRequired().HasMaxLength(2000);
            b.Property<bool>("IsAdminReply");
            b.Property<Guid?>("UserId");
            b.Property<string?>("CommenterName").HasMaxLength(200);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("ProductReviewId", "CreatedAt");
            b.ToTable("ProductReviewDetails");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductReviewHelpfulness", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("ProductReviewId");
            b.Property<Guid>("CustomerId");
            b.Property<bool>("IsHelpful");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("ProductReviewId", "CustomerId").IsUnique();
            b.ToTable("ProductReviewHelpfulnesses");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductReview", b =>
        {
            b.HasOne("BasicCommerce.Domain.Entities.Product", null)
                .WithMany()
                .HasForeignKey("ProductId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
            b.HasOne("BasicCommerce.Domain.Entities.Customer", null)
                .WithMany()
                .HasForeignKey("CustomerId")
                .OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductReviewDetail", b =>
        {
            b.HasOne("BasicCommerce.Domain.Entities.ProductReview", null)
                .WithMany("Details")
                .HasForeignKey("ProductReviewId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.ProductReviewHelpfulness", b =>
        {
            b.HasOne("BasicCommerce.Domain.Entities.ProductReview", null)
                .WithMany()
                .HasForeignKey("ProductReviewId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

#pragma warning restore 612, 618
    }
}
