// <auto-generated />
using BasicCommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicCommerce.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BasicCommerceDbContext))]
partial class BasicCommerceDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Tenant", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("Name").IsRequired().HasMaxLength(200);
            b.Property<string>("Slug").IsRequired().HasMaxLength(100);
            b.Property<string>("ContactEmail").IsRequired().HasMaxLength(256);
            b.Property<string>("ContactPhone").HasMaxLength(20);
            b.Property<string>("BusinessIdentificationNumber").HasMaxLength(50);
            b.Property<string>("VatRegistrationNumber").HasMaxLength(50);
            b.Property<string>("CurrencyCode").IsRequired().HasMaxLength(3).HasDefaultValue("BDT");
            b.Property<string>("DefaultLanguage").IsRequired().HasMaxLength(10).HasDefaultValue("en");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.Property<Guid?>("CreatedBy");
            b.Property<Guid?>("UpdatedBy");
            b.HasKey("Id");
            b.HasIndex("Slug").IsUnique();
            b.ToTable("Tenants");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Store", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Name").IsRequired().HasMaxLength(200);
            b.Property<string>("Code").IsRequired().HasMaxLength(20);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("TenantId", "Code").IsUnique();
            b.ToTable("Stores");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Email").IsRequired().HasMaxLength(256);
            b.Property<string>("FirstName").IsRequired().HasMaxLength(100);
            b.Property<string>("LastName").IsRequired().HasMaxLength(100);
            b.Property<string>("EmployeeCode").IsRequired().HasMaxLength(20);
            b.Property<string>("PasswordHash").HasMaxLength(500);
            b.Property<string>("Role").IsRequired().HasMaxLength(30);
            b.Property<Guid?>("StoreId");
            b.Property<string>("GoogleId").HasMaxLength(200);
            b.Property<string>("MicrosoftId").HasMaxLength(200);
            b.Property<string>("AuthProvider").IsRequired().HasMaxLength(20).HasDefaultValue("Local");
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<string>("PreferredLanguage").IsRequired().HasMaxLength(10).HasDefaultValue("en");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("TenantId", "EmployeeCode").IsUnique();
            b.ToTable("Users");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Product", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("Sku").IsRequired().HasMaxLength(50);
            b.Property<string>("Barcode").IsRequired().HasMaxLength(100);
            b.Property<string>("Plu").HasMaxLength(20);
            b.Property<string>("Name").IsRequired().HasMaxLength(200);
            b.Property<string>("NameBn").IsRequired().HasMaxLength(200);
            b.Property<Guid>("CategoryId");
            b.Property<Guid>("VatRateId");
            b.Property<bool>("IsWeightBased").HasDefaultValue(false);
            b.Property<bool>("IsAgeRestricted").HasDefaultValue(false);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("Barcode").IsUnique();
            b.HasIndex("TenantId", "Sku").IsUnique();
            b.ToTable("Products");
        });

        modelBuilder.Entity("BasicCommerce.Domain.Entities.Transaction", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("TenantId");
            b.Property<string>("TransactionNumber").IsRequired().HasMaxLength(50);
            b.Property<Guid>("StoreId");
            b.Property<Guid>("TerminalId");
            b.Property<Guid>("CashierId");
            b.Property<Guid?>("CustomerId");
            b.Property<string>("TransactionStatus").IsRequired().HasMaxLength(20).HasDefaultValue("Open");
            b.Property<string>("Type").IsRequired().HasMaxLength(20).HasDefaultValue("Sale");
            b.Property<decimal>("SubTotal").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("TaxTotal").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("DiscountTotal").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("Total").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("AmountPaid").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<decimal>("ChangeDue").HasPrecision(18, 4).HasDefaultValue(0m);
            b.Property<bool>("IsSynced").HasDefaultValue(true);
            b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Active");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("CompletedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("TransactionNumber").IsUnique();
            b.HasIndex("TenantId", "StoreId", "CreatedAt");
            b.ToTable("Transactions");
        });

#pragma warning restore 612, 618
    }
}
