namespace BasicCommerce.Application.Common;

public static class BangladeshDistricts
{
    public static readonly IReadOnlyDictionary<string, string> All =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["BAGER"] = "Bagerhat",
            ["BANDA"] = "Bandarban",
            ["BARGU"] = "Barguna",
            ["BARIS"] = "Barishal",
            ["BHOLA"] = "Bhola",
            ["BOGUR"] = "Bogura",
            ["BRAHM"] = "Brahmanbaria",
            ["CHAND"] = "Chandpur",
            ["CHAPN"] = "Chapai Nawabganj",
            ["CHATT"] = "Chattogram",
            ["CHUAD"] = "Chuadanga",
            ["CUMIL"] = "Cumilla",
            ["COXSB"] = "Cox's Bazar",
            ["DHAKA"] = "Dhaka",
            ["DINAJ"] = "Dinajpur",
            ["FARID"] = "Faridpur",
            ["FENI"]  = "Feni",
            ["GAIBA"] = "Gaibandha",
            ["GAZIP"] = "Gazipur",
            ["GOPAL"] = "Gopalganj",
            ["HABIG"] = "Habiganj",
            ["JAMAL"] = "Jamalpur",
            ["JASHO"] = "Jashore",
            ["JHALO"] = "Jhalokati",
            ["JHENA"] = "Jhenaidah",
            ["JOYPU"] = "Joypurhat",
            ["KHAGR"] = "Khagrachari",
            ["KHULN"] = "Khulna",
            ["KISHO"] = "Kishoreganj",
            ["KURIG"] = "Kurigram",
            ["KUSHT"] = "Kushtia",
            ["LAKSH"] = "Lakshmipur",
            ["LALMO"] = "Lalmonirhat",
            ["MADAR"] = "Madaripur",
            ["MAGUR"] = "Magura",
            ["MANIK"] = "Manikganj",
            ["MEHER"] = "Meherpur",
            ["MOULV"] = "Moulvibazar",
            ["MUNSH"] = "Munshiganj",
            ["MYMNS"] = "Mymensingh",
            ["NAOGN"] = "Naogaon",
            ["NARAL"] = "Narail",
            ["NARAY"] = "Narayanganj",
            ["NARSG"] = "Narsingdi",
            ["NATOR"] = "Natore",
            ["NETRO"] = "Netrokona",
            ["NILPH"] = "Nilphamari",
            ["NOAKH"] = "Noakhali",
            ["PABNA"] = "Pabna",
            ["PANCH"] = "Panchagarh",
            ["PATUA"] = "Patuakhali",
            ["PIROJ"] = "Pirojpur",
            ["RAJBA"] = "Rajbari",
            ["RAJSH"] = "Rajshahi",
            ["RANGM"] = "Rangamati",
            ["RANGP"] = "Rangpur",
            ["SATKH"] = "Satkhira",
            ["SHARI"] = "Shariatpur",
            ["SHERP"] = "Sherpur",
            ["SIRAJ"] = "Sirajganj",
            ["SUNAM"] = "Sunamganj",
            ["SYLHE"] = "Sylhet",
            ["TANGI"] = "Tangail",
            ["THAKU"] = "Thakurgaon",
        };

    public static bool IsValid(string? code) =>
        !string.IsNullOrWhiteSpace(code) && All.ContainsKey(code);
}
